import { DataSource } from 'typeorm';
import { Product } from '../../modules/products/entity/product.entity';
import { Shop } from '../../modules/shop/entity/shop.entity';
import { Category } from '../../modules/category/entity/category.entity';
import { SubCategory } from '../../modules/subcategory/entity/subcategory.entity';
import dataSource from '../../config/data-source';

export class ProductSeed {
  private dataSource: DataSource;

  constructor() {
    this.dataSource = dataSource;
  }

  async run() {
    await this.dataSource.initialize();
    const productRepo = this.dataSource.getRepository(Product);
    const shopRepo = this.dataSource.getRepository(Shop);
    const categoryRepo = this.dataSource.getRepository(Category);
    const subCategoryRepo = this.dataSource.getRepository(SubCategory);

    // Get shops, categories, and subcategories
    const shops = await shopRepo.find();
    const categories = await categoryRepo.find();
    const subCategories = await subCategoryRepo.find();

    const categoryMap = new Map(categories.map(cat => [cat.name, cat]));
    const subCategoryMap = new Map(subCategories.map(sub => [sub.name, sub]));

    const products: Partial<Product>[] = [
      // Electronics Products
      {
        name: 'iPhone 15 Pro',
        description: 'Latest iPhone with advanced features',
        longDescription: 'The iPhone 15 Pro features a titanium design, A17 Pro chip, and advanced camera system.',
        mrp: 119999,
        sellingPrice: 109999,
        discountPercentage: 8,
        stockQuantity: 50,
        isAvailable: true,
        lowStockThreshold: 10,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'Apple',
        isVeg: true,
        expiryDays: undefined,
        images: ['iphone15pro.jpg', 'iphone15pro2.jpg'],
        category: categoryMap.get('Electronics'),
        subCategory: subCategoryMap.get('Smartphones'),
        shop: shops[0],
      },
      {
        name: 'Samsung Galaxy S24',
        description: 'Flagship Android smartphone',
        longDescription: 'Samsung Galaxy S24 with AI features and premium design.',
        mrp: 89999,
        sellingPrice: 79999,
        discountPercentage: 11,
        stockQuantity: 75,
        isAvailable: true,
        lowStockThreshold: 15,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'Samsung',
        isVeg: true,
        expiryDays: undefined,
        images: ['galaxys24.jpg', 'galaxys242.jpg'],
        category: categoryMap.get('Electronics'),
        subCategory: subCategoryMap.get('Smartphones'),
        shop: shops[0],
      },
      {
        name: 'MacBook Pro 16"',
        description: 'Professional laptop for creators',
        longDescription: 'MacBook Pro 16" with M3 Pro chip, perfect for professional work.',
        mrp: 249999,
        sellingPrice: 229999,
        discountPercentage: 8,
        stockQuantity: 25,
        isAvailable: true,
        lowStockThreshold: 5,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'Apple',
        isVeg: true,
        expiryDays: undefined,
        images: ['macbookpro16.jpg'],
        category: categoryMap.get('Electronics'),
        subCategory: subCategoryMap.get('Laptops'),
        shop: shops[0],
      },
      {
        name: 'Sony WH-1000XM5',
        description: 'Premium noise-cancelling headphones',
        longDescription: 'Industry-leading noise cancellation with exceptional sound quality.',
        mrp: 29999,
        sellingPrice: 24999,
        discountPercentage: 17,
        stockQuantity: 100,
        isAvailable: true,
        lowStockThreshold: 20,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'Sony',
        isVeg: true,
        expiryDays: undefined,
        images: ['sonyxm5.jpg'],
        category: categoryMap.get('Electronics'),
        subCategory: subCategoryMap.get('Headphones'),
        shop: shops[0],
      },
      {
        name: 'Apple Watch Series 9',
        description: 'Advanced smartwatch with health features',
        longDescription: 'Apple Watch Series 9 with advanced health monitoring and fitness tracking.',
        mrp: 44999,
        sellingPrice: 39999,
        discountPercentage: 11,
        stockQuantity: 60,
        isAvailable: true,
        lowStockThreshold: 12,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'Apple',
        isVeg: true,
        expiryDays: undefined,
        images: ['applewatch9.jpg'],
        category: categoryMap.get('Electronics'),
        subCategory: subCategoryMap.get('Smart Watches'),
        shop: shops[0],
      },

      // Clothing Products
      {
        name: 'Men\'s Cotton T-Shirt',
        description: 'Comfortable cotton t-shirt for men',
        longDescription: '100% cotton t-shirt, available in multiple colors and sizes.',
        mrp: 999,
        sellingPrice: 699,
        discountPercentage: 30,
        stockQuantity: 200,
        isAvailable: true,
        lowStockThreshold: 40,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'Fashion Hub',
        isVeg: true,
        expiryDays: undefined,
        images: ['mens-tshirt.jpg'],
        category: categoryMap.get('Clothing'),
        subCategory: subCategoryMap.get('Men\'s T-Shirts'),
        shop: shops[1],
      },
      {
        name: 'Women\'s Summer Dress',
        description: 'Elegant summer dress for women',
        longDescription: 'Light and breathable summer dress, perfect for casual occasions.',
        mrp: 1999,
        sellingPrice: 1499,
        discountPercentage: 25,
        stockQuantity: 80,
        isAvailable: true,
        lowStockThreshold: 16,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'Fashion Hub',
        isVeg: true,
        expiryDays: undefined,
        images: ['summer-dress.jpg'],
        category: categoryMap.get('Clothing'),
        subCategory: subCategoryMap.get('Women\'s Dresses'),
        shop: shops[1],
      },
      {
        name: 'Kids School Uniform',
        description: 'Comfortable school uniform for kids',
        longDescription: 'Durable and comfortable school uniform for daily wear.',
        mrp: 1299,
        sellingPrice: 999,
        discountPercentage: 23,
        stockQuantity: 150,
        isAvailable: true,
        lowStockThreshold: 30,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'Fashion Hub',
        isVeg: true,
        expiryDays: undefined,
        images: ['school-uniform.jpg'],
        category: categoryMap.get('Clothing'),
        subCategory: subCategoryMap.get('Kids Clothing'),
        shop: shops[1],
      },
      {
        name: 'Running Shoes',
        description: 'Professional running shoes',
        longDescription: 'Lightweight running shoes with advanced cushioning technology.',
        mrp: 4999,
        sellingPrice: 3999,
        discountPercentage: 20,
        stockQuantity: 120,
        isAvailable: true,
        lowStockThreshold: 24,
        unit: 'pair',
        unitValue: 1,
        packSize: '1 pair',
        brand: 'SportPro',
        isVeg: true,
        expiryDays: undefined,
        images: ['running-shoes.jpg'],
        category: categoryMap.get('Clothing'),
        subCategory: subCategoryMap.get('Shoes'),
        shop: shops[1],
      },
      {
        name: 'Leather Wallet',
        description: 'Genuine leather wallet',
        longDescription: 'Premium leather wallet with multiple card slots.',
        mrp: 1999,
        sellingPrice: 1499,
        discountPercentage: 25,
        stockQuantity: 90,
        isAvailable: true,
        lowStockThreshold: 18,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'Fashion Hub',
        isVeg: true,
        expiryDays: undefined,
        images: ['leather-wallet.jpg'],
        category: categoryMap.get('Clothing'),
        subCategory: subCategoryMap.get('Accessories'),
        shop: shops[1],
      },

      // Home & Garden Products
      {
        name: 'Office Chair Ergonomic',
        description: 'Comfortable ergonomic office chair',
        longDescription: 'Adjustable ergonomic chair with lumbar support for long working hours.',
        mrp: 8999,
        sellingPrice: 6999,
        discountPercentage: 22,
        stockQuantity: 40,
        isAvailable: true,
        lowStockThreshold: 8,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'HomeComfort',
        isVeg: true,
        expiryDays: undefined,
        images: ['office-chair.jpg'],
        category: categoryMap.get('Home & Garden'),
        subCategory: subCategoryMap.get('Furniture'),
        shop: shops[0],
      },
      {
        name: 'Coffee Maker Deluxe',
        description: 'Automatic coffee maker',
        longDescription: 'Programmable coffee maker with built-in grinder.',
        mrp: 7999,
        sellingPrice: 5999,
        discountPercentage: 25,
        stockQuantity: 60,
        isAvailable: true,
        lowStockThreshold: 12,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'BrewMaster',
        isVeg: true,
        expiryDays: undefined,
        images: ['coffee-maker.jpg'],
        category: categoryMap.get('Home & Garden'),
        subCategory: subCategoryMap.get('Kitchen Appliances'),
        shop: shops[0],
      },
      {
        name: 'Garden Tool Set',
        description: 'Complete garden tool set',
        longDescription: 'Professional-grade garden tools for all your gardening needs.',
        mrp: 3999,
        sellingPrice: 2999,
        discountPercentage: 25,
        stockQuantity: 30,
        isAvailable: true,
        lowStockThreshold: 6,
        unit: 'set',
        unitValue: 1,
        packSize: '1 set',
        brand: 'GardenPro',
        isVeg: true,
        expiryDays: undefined,
        images: ['garden-tools.jpg'],
        category: categoryMap.get('Home & Garden'),
        subCategory: subCategoryMap.get('Garden Tools'),
        shop: shops[0],
      },
      {
        name: 'Wall Art Canvas',
        description: 'Decorative wall art canvas',
        longDescription: 'Modern abstract wall art to enhance your home decor.',
        mrp: 2999,
        sellingPrice: 1999,
        discountPercentage: 33,
        stockQuantity: 25,
        isAvailable: true,
        lowStockThreshold: 5,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'ArtSpace',
        isVeg: true,
        expiryDays: undefined,
        images: ['wall-art.jpg'],
        category: categoryMap.get('Home & Garden'),
        subCategory: subCategoryMap.get('Home Decor'),
        shop: shops[0],
      },

      // Sports & Outdoors Products
      {
        name: 'Yoga Mat Premium',
        description: 'Non-slip yoga mat',
        longDescription: 'Extra thick yoga mat with superior grip and cushioning.',
        mrp: 1999,
        sellingPrice: 1499,
        discountPercentage: 25,
        stockQuantity: 100,
        isAvailable: true,
        lowStockThreshold: 20,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'FitGear',
        isVeg: true,
        expiryDays: undefined,
        images: ['yoga-mat.jpg'],
        category: categoryMap.get('Sports & Outdoors'),
        subCategory: subCategoryMap.get('Fitness Equipment'),
        shop: shops[0],
      },
      {
        name: 'Camping Tent 4-Person',
        description: 'Spacious camping tent',
        longDescription: 'Waterproof 4-person camping tent with easy setup.',
        mrp: 4999,
        sellingPrice: 3999,
        discountPercentage: 20,
        stockQuantity: 35,
        isAvailable: true,
        lowStockThreshold: 7,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'CampPro',
        isVeg: true,
        expiryDays: undefined,
        images: ['camping-tent.jpg'],
        category: categoryMap.get('Sports & Outdoors'),
        subCategory: subCategoryMap.get('Camping Gear'),
        shop: shops[0],
      },
      {
        name: 'Sports Water Bottle',
        description: 'Insulated sports water bottle',
        longDescription: 'Double-walled insulated water bottle keeps drinks cold for 24 hours.',
        mrp: 799,
        sellingPrice: 599,
        discountPercentage: 25,
        stockQuantity: 200,
        isAvailable: true,
        lowStockThreshold: 40,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'FitGear',
        isVeg: true,
        expiryDays: undefined,
        images: ['water-bottle.jpg'],
        category: categoryMap.get('Sports & Outdoors'),
        subCategory: subCategoryMap.get('Sports Clothing'),
        shop: shops[0],
      },

      // Books & Media Products
      {
        name: 'Fiction Novel Collection',
        description: 'Bestselling fiction novels',
        longDescription: 'Collection of award-winning fiction novels from various authors.',
        mrp: 1299,
        sellingPrice: 999,
        discountPercentage: 23,
        stockQuantity: 150,
        isAvailable: true,
        lowStockThreshold: 30,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'BookWorld',
        isVeg: true,
        expiryDays: undefined,
        images: ['fiction-novels.jpg'],
        category: categoryMap.get('Books & Media'),
        subCategory: subCategoryMap.get('Fiction Books'),
        shop: shops[1],
      },
      {
        name: 'Programming Guide 2024',
        description: 'Latest programming guide',
        longDescription: 'Comprehensive guide to modern programming languages and frameworks.',
        mrp: 1899,
        sellingPrice: 1499,
        discountPercentage: 21,
        stockQuantity: 80,
        isAvailable: true,
        lowStockThreshold: 16,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'TechBooks',
        isVeg: true,
        expiryDays: undefined,
        images: ['programming-guide.jpg'],
        category: categoryMap.get('Books & Media'),
        subCategory: subCategoryMap.get('Educational Books'),
        shop: shops[1],
      },
      {
        name: 'Movie Collection Box Set',
        description: 'Popular movie collection',
        longDescription: 'Box set of critically acclaimed movies in high definition.',
        mrp: 2999,
        sellingPrice: 1999,
        discountPercentage: 33,
        stockQuantity: 40,
        isAvailable: true,
        lowStockThreshold: 8,
        unit: 'set',
        unitValue: 1,
        packSize: '1 set',
        brand: 'MovieStudio',
        isVeg: true,
        expiryDays: undefined,
        images: ['movie-boxset.jpg'],
        category: categoryMap.get('Books & Media'),
        subCategory: subCategoryMap.get('Movies & TV Shows'),
        shop: shops[1],
      },

      // Health & Beauty Products
      {
        name: 'Face Cream Daily',
        description: 'Daily moisturizing face cream',
        longDescription: 'Lightweight daily face cream with SPF 30 protection.',
        mrp: 899,
        sellingPrice: 699,
        discountPercentage: 22,
        stockQuantity: 120,
        isAvailable: true,
        lowStockThreshold: 24,
        unit: 'piece',
        unitValue: 1,
        packSize: '1 piece',
        brand: 'BeautyCare',
        isVeg: true,
        expiryDays: 730,
        images: ['face-cream.jpg'],
        category: categoryMap.get('Health & Beauty'),
        subCategory: subCategoryMap.get('Skincare Products'),
        shop: shops[1],
      },
      {
        name: 'Lipstick Set Premium',
        description: 'Premium lipstick collection',
        longDescription: 'Set of 6 premium shades with long-lasting formula.',
        mrp: 1999,
        sellingPrice: 1499,
        discountPercentage: 25,
        stockQuantity: 90,
        isAvailable: true,
        lowStockThreshold: 18,
        unit: 'set',
        unitValue: 1,
        packSize: '1 set',
        brand: 'BeautyCare',
        isVeg: true,
        expiryDays: 1095,
        images: ['lipstick-set.jpg'],
        category: categoryMap.get('Health & Beauty'),
        subCategory: subCategoryMap.get('Makeup'),
        shop: shops[1],
      },
      {
        name: 'Shampoo Herbal',
        description: 'Natural herbal shampoo',
        longDescription: 'Gentle herbal shampoo for all hair types.',
        mrp: 499,
        sellingPrice: 399,
        discountPercentage: 20,
        stockQuantity: 200,
        isAvailable: true,
        lowStockThreshold: 40,
        unit: 'bottle',
        unitValue: 200,
        packSize: '200ml bottle',
        brand: 'NatureCare',
        isVeg: true,
        expiryDays: 1095,
        images: ['shampoo.jpg'],
        category: categoryMap.get('Health & Beauty'),
        subCategory: subCategoryMap.get('Personal Care'),
        shop: shops[1],
      },

      // Food & Beverages Products
      {
        name: 'Organic Honey Pure',
        description: 'Pure organic honey',
        longDescription: '100% pure organic honey from local farms.',
        mrp: 599,
        sellingPrice: 499,
        discountPercentage: 17,
        stockQuantity: 80,
        isAvailable: true,
        lowStockThreshold: 16,
        unit: 'jar',
        unitValue: 500,
        packSize: '500g jar',
        brand: 'NatureFresh',
        isVeg: true,
        expiryDays: 730,
        images: ['organic-honey.jpg'],
        category: categoryMap.get('Food & Beverages'),
        subCategory: subCategoryMap.get('Groceries'),
        shop: shops[0],
      },
      {
        name: 'Green Tea Premium',
        description: 'Premium green tea leaves',
        longDescription: 'High-quality green tea leaves from premium gardens.',
        mrp: 899,
        sellingPrice: 699,
        discountPercentage: 22,
        stockQuantity: 100,
        isAvailable: true,
        lowStockThreshold: 20,
        unit: 'pack',
        unitValue: 100,
        packSize: '100g pack',
        brand: 'TeaMaster',
        isVeg: true,
        expiryDays: 1095,
        images: ['green-tea.jpg'],
        category: categoryMap.get('Food & Beverages'),
        subCategory: subCategoryMap.get('Groceries'),
        shop: shops[0],
      },

      // Toys & Games Products
      {
        name: 'Chess Board Premium',
        description: 'Professional chess board',
        longDescription: 'Handcrafted wooden chess board with premium pieces.',
        mrp: 2999,
        sellingPrice: 1999,
        discountPercentage: 33,
        stockQuantity: 30,
        isAvailable: true,
        lowStockThreshold: 6,
        unit: 'set',
        unitValue: 1,
        packSize: '1 set',
        brand: 'GameWorld',
        isVeg: true,
        expiryDays: undefined,
        images: ['chess-board.jpg'],
        category: categoryMap.get('Toys & Games'),
        subCategory: subCategoryMap.get('Board Games'),
        shop: shops[1],
      },
      {
        name: 'Science Kit Advanced',
        description: 'Educational science kit',
        longDescription: 'Complete science experiment kit for students.',
        mrp: 1999,
        sellingPrice: 1499,
        discountPercentage: 25,
        stockQuantity: 60,
        isAvailable: true,
        lowStockThreshold: 12,
        unit: 'kit',
        unitValue: 1,
        packSize: '1 kit',
        brand: 'EduPlay',
        isVeg: true,
        expiryDays: undefined,
        images: ['science-kit.jpg'],
        category: categoryMap.get('Toys & Games'),
        subCategory: subCategoryMap.get('Educational Toys'),
        shop: shops[1],
      },
    ];

    for (const productData of products) {
      const existingProduct = await productRepo.findOne({
        where: { name: productData.name },
      });

      if (!existingProduct) {
        const product = productRepo.create(productData);
        await productRepo.save(product);
      }
    }

    await this.dataSource.destroy();
  }
}
